const STOCKPILE_API='/.netlify/functions/stockpile';
const WORLD_API='/.netlify/functions/world-v2';
const GAME_KEY='gptworld-day1';
const CLIENT_KEY='gptworld-client-id';
let panel,counts={},lastNear=false,depositing=false;

function readGame(){try{return JSON.parse(localStorage.getItem(GAME_KEY))||{}}catch{return{}}}
function writeInventory(inv){if(!inv)return;const game=readGame();game.inventory={wood:Number(inv.wood||0),stone:Number(inv.stone||0),herbs:Number(inv.herbs||0)};localStorage.setItem(GAME_KEY,JSON.stringify(game));for(const [k,id] of Object.entries({wood:'woodCount',stone:'stoneCount',herbs:'herbCount'})){const el=document.getElementById(id);if(el)el.textContent=String(game.inventory[k]||0)}window.dispatchEvent(new CustomEvent('gptworld:inventory-state',{detail:game.inventory}))}
function nearStorehouse(){const g=readGame();return Math.hypot(Number(g.x||0)-4,Number(g.z||0)-7)<4.2}
function style(el,css){Object.assign(el.style,css)}
function toast(message){const t=document.getElementById('toast');if(!t)return;t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3200)}
function build(){panel=document.createElement('section');panel.id='day3Stockpile';panel.setAttribute('aria-label','Settlement stockpile');style(panel,{position:'fixed',left:'50%',bottom:'max(150px, calc(env(safe-area-inset-bottom) + 138px))',transform:'translateX(-50%)',zIndex:'25',display:'none',width:'min(92vw,420px)',padding:'12px 14px',borderRadius:'14px',background:'rgba(20,29,22,.94)',color:'#f5eddc',boxShadow:'0 10px 30px rgba(0,0,0,.3)',fontFamily:'system-ui,sans-serif'});panel.innerHTML='<div style="font-size:11px;letter-spacing:.12em;opacity:.7">DAY 3 · THE STOREHOUSE OPENS</div><strong style="display:block;margin:4px 0 8px">Settlement Stockpile</strong><div id="stockpileCounts" style="display:flex;gap:14px;font-size:14px;margin-bottom:8px"></div><div style="display:flex;gap:8px;flex-wrap:wrap"><button data-r="wood">Deposit 1 wood</button><button data-r="stone">Deposit 1 stone</button><button data-r="herbs">Deposit 1 herb</button></div><small style="display:block;margin-top:8px;opacity:.72">Resources stored here belong to the settlement and persist for everyone.</small>';document.body.appendChild(panel);counts=panel.querySelector('#stockpileCounts');for(const b of panel.querySelectorAll('button')){style(b,{padding:'8px 10px',border:'0',borderRadius:'9px',fontWeight:'700',cursor:'pointer'});b.addEventListener('click',()=>deposit(b.dataset.r))}}
function renderStockpile(s){if(!counts)return;counts.innerHTML=`<span>🪵 ${Number(s?.wood||0)}</span><span>🪨 ${Number(s?.stone||0)}</span><span>🌿 ${Number(s?.herbs||0)}</span>`}
async function refresh(){try{const id=localStorage.getItem(CLIENT_KEY)||'';const r=await fetch(`${STOCKPILE_API}?clientId=${encodeURIComponent(id)}`,{cache:'no-store'});const d=await r.json();if(d.ok){renderStockpile(d.stockpile);if(d.inventory)writeInventory(d.inventory)}}catch{}}
async function ensureRegistered(id){const game=readGame();const r=await fetch(WORLD_API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({clientId:id,name:game.playerName||'Traveler',x:game.x??0,z:game.z??12})});const d=await r.json();return Boolean(d.ok)}
async function postDeposit(id,resource){const r=await fetch(STOCKPILE_API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({clientId:id,action:'deposit',resource,amount:1})});return r.json()}
async function deposit(resource){if(depositing)return;const id=localStorage.getItem(CLIENT_KEY);if(!id){toast('The shared world is still connecting.');return}depositing=true;try{let d=await postDeposit(id,resource);if(!d.ok&&d.error==='player_not_registered'){const registered=await ensureRegistered(id);if(registered)d=await postDeposit(id,resource)}if(!d.ok){if(d.error==='not_enough_materials')toast(`You do not have enough ${resource}.`);else if(d.error==='player_not_registered')toast('Your traveler record is still connecting. Try again in a moment.');else toast(`Storehouse error: ${d.error||'server_error'}${d.detail?` — ${d.detail}`:''}`);return}writeInventory(d.inventory);renderStockpile(d.stockpile);toast(`Deposited 1 ${resource} into the settlement stockpile.`)}catch(err){toast(`The storehouse could not reach the shared world${err?.message?`: ${err.message}`:'.'}`)}finally{depositing=false}}
function tick(){const welcome=document.getElementById('welcome');const near=!welcome||welcome.hidden?nearStorehouse():false;if(panel)panel.style.display=near?'block':'none';if(near&&!lastNear)refresh();lastNear=near}
build();setInterval(tick,450);setInterval(refresh,15000);window.addEventListener('focus',refresh);