const ECOSYSTEM_API='/.netlify/functions/world';
let ecosystemState=null;
let naturalHistoryOpen=false;
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

function ensureUI(){
  if(document.getElementById('naturalHistoryButton'))return;
  const button=document.createElement('button');button.id='naturalHistoryButton';button.type='button';button.textContent='🌱 Natural History';button.style.cssText='position:fixed;right:14px;bottom:14px;z-index:42;border:1px solid rgba(255,255,255,.16);border-radius:999px;padding:10px 14px;background:rgba(20,34,24,.92);color:#f4efdf;font:700 13px system-ui,sans-serif;box-shadow:0 8px 24px rgba(0,0,0,.3);cursor:pointer';button.addEventListener('click',toggle);document.body.appendChild(button);
  const panel=document.createElement('section');panel.id='naturalHistoryPanel';panel.style.cssText='position:fixed;inset:64px 14px 82px auto;z-index:41;width:min(430px,calc(100vw - 28px));overflow:auto;background:rgba(17,28,20,.97);color:#f4efdf;border:1px solid rgba(255,255,255,.14);border-radius:18px;padding:18px;display:none;font-family:system-ui,sans-serif';panel.innerHTML='<div id="naturalHistoryContent">Loading the living record…</div>';document.body.appendChild(panel);
}

function render(){
  const el=document.getElementById('naturalHistoryContent');if(!el||!ecosystemState)return;const e=ecosystemState;const species=Array.isArray(e.species)?e.species:[];const extinct=Array.isArray(e.extinct)?e.extinct:[];const c=e.climate||{};
  el.innerHTML=`<div style="display:flex;justify-content:space-between;gap:12px"><div><small style="opacity:.6;letter-spacing:.12em">ECOLOGY SIM</small><h2 style="margin:4px 0">Natural History</h2></div><button id="closeNaturalHistory" type="button" style="border:0;background:transparent;color:#fff;font-size:24px">×</button></div><p style="font-size:13px;opacity:.76">Ecology runs independently from GPTWorld's numbered narrative day. The main world engine now renders its plants and animals directly from this persistent state.</p><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:14px 0"><div style="padding:9px;background:rgba(255,255,255,.06);border-radius:10px"><small>Eco year</small><b style="display:block;font-size:20px">${Number(e.simulatedYear||0)}</b></div><div style="padding:9px;background:rgba(255,255,255,.06);border-radius:10px"><small>Living</small><b style="display:block;font-size:20px">${species.length}</b></div><div style="padding:9px;background:rgba(255,255,255,.06);border-radius:10px"><small>Extinct</small><b style="display:block;font-size:20px">${extinct.length}</b></div></div><div style="font-size:13px;margin-bottom:12px"><b>Ecology climate:</b> ${Number(c.temperatureC||0).toFixed(1)}°C · rainfall ${Math.round(Number(c.rainfall||0)*100)}% · fertility ${Math.round(Number(c.fertility||0)*100)}%</div>${species.map(s=>`<article style="padding:10px 0;border-top:1px solid rgba(255,255,255,.1)"><div style="display:flex;justify-content:space-between"><b>${esc(s.name)}</b><span style="opacity:.65;font-size:12px">${esc(s.kind)}</span></div><div style="font-size:13px;opacity:.8">Population ${Number(s.population||0).toLocaleString()} · ${esc(s.habitat||'unknown habitat')}</div></article>`).join('')}`;
  document.getElementById('closeNaturalHistory')?.addEventListener('click',toggle);
}
function toggle(){naturalHistoryOpen=!naturalHistoryOpen;const p=document.getElementById('naturalHistoryPanel');if(!p)return;p.style.display=naturalHistoryOpen?'block':'none';if(naturalHistoryOpen){render();refresh();}}
async function refresh(){try{const r=await fetch(ECOSYSTEM_API,{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json();ecosystemState=d.ecosystem||d.world?.ecosystem||null;if(!ecosystemState)throw new Error('No ecology state');const b=document.getElementById('naturalHistoryButton');if(b)b.textContent=`🌱 Eco ${Number(ecosystemState.simulatedYear||0)}`;if(naturalHistoryOpen)render();}catch(e){console.error('Ecology status failed',e);}}
ensureUI();refresh();setInterval(refresh,30000);
