import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/+esm';

const BUILDINGS={
  inn:{name:'Wayfarer Inn',wall:0x9b815c,trim:0x5b3b2d,floor:0x79553a,resident:'Mara the Keeper',residentColor:0x7b4f42,objects:[['guest bed','bed',-4,-3,'A warm bed waits for a weary traveler.'],['hearth','hearth',4,-3,'The inn hearth gives off a steady warmth.'],['guest ledger','desk',3.5,2.4,'The ledger records travelers who passed through the settlement.']]},
  smithy:{name:'Smithy',wall:0x8c7254,trim:0x4a3328,floor:0x625044,resident:'Tovan the Smith',residentColor:0x455c6b,objects:[['forge','hearth',-4,-3,'The forge is hot. Future crafting work will happen here.'],['anvil','anvil',2.8,-1.8,'A heavy iron anvil stands ready for smithing.'],['tool bench','desk',3.8,2.8,'Hammers, tongs, and unfinished tools cover the bench.']]},
  storehouse:{name:'Storehouse',wall:0x9a8865,trim:0x5a4431,floor:0x725940,resident:'Storehouse Keeper',residentColor:0x6a5d48,objects:[['supply crates','crates',-3.8,-2.8,'These crates hold the settlement’s shared supplies.'],['storage shelves','shelves',4,-2.8,'The shelves are sorted for counting and distribution.'],['inventory ledger','desk',3.3,2.5,'The ledger tracks community resource deposits.']]},
  healer:{name:'Healer’s Cottage',wall:0x967b58,trim:0x60402e,floor:0x786148,resident:'Edda the Healer',residentColor:0x697348,objects:[['treatment bed','bed',-3.8,-2.8,'A clean treatment bed is ready for the next patient.'],['herb cabinet','shelves',4,-2.7,'Dried medicinal herbs fill the cabinet.'],['medicine table','herbs',3.2,2.5,'Remedies and simple instruments are arranged here.']]},
  council:{name:'Council Hall',wall:0x8b7658,trim:0x4c3529,floor:0x6f553d,resident:'Council Steward',residentColor:0x625274,objects:[['council table','table',0,-1,'The settlement gathers here to decide what comes next.'],['world map','map',-4.7,-5.8,'A hand-drawn map shows the valley, river, and trails.'],['notice board','board',4.7,-5.8,'Community plans and announcements are pinned here.']]}
};
const id=new URLSearchParams(location.search).get('building'),config=Object.hasOwn(BUILDINGS,id)?BUILDINGS[id]:null;
const worldEl=document.getElementById('world'),loading=document.getElementById('loading'),loadingTitle=document.getElementById('loadingTitle'),loadingMessage=document.getElementById('loadingMessage'),retry=document.getElementById('retry'),promptEl=document.getElementById('prompt'),toastEl=document.getElementById('toast'),actionButton=document.getElementById('actionButton'),exitWorld=document.getElementById('exitWorld');
let renderer,scene,camera,player,clock,level=1,running=false,toastTimer,nearest=null,joystickPointer=null,joystickX=0,joystickY=0;
const keys=new Set(),blockers=[],interactables=[],velocity=new THREE.Vector3(),desired=new THREE.Vector3(),cameraTarget=new THREE.Vector3();
const material=(color,roughness=.92)=>new THREE.MeshStandardMaterial({color,roughness});
function box(parent,color,size,pos,roughness=.92){const mesh=new THREE.Mesh(new THREE.BoxGeometry(...size),material(color,roughness));mesh.position.set(...pos);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh}
function block(x,z,w,d,pad=.18){blockers.push({minX:x-w/2-pad,maxX:x+w/2+pad,minZ:z-d/2-pad,maxZ:z+d/2+pad})}
function register(name,object,radius,message){interactables.push({name,object,radius,message})}

function humanoid({outfit=0x8b7650,skin=0xe0b586,hair=0x3a2b23,accent=0x49392c,pack=true}={}){const g=new THREE.Group(),torso=new THREE.Mesh(new THREE.CylinderGeometry(.34,.43,.86,8),material(outfit)),head=new THREE.Mesh(new THREE.SphereGeometry(.30,12,9),material(skin)),hairMesh=new THREE.Mesh(new THREE.SphereGeometry(.305,10,7,0,Math.PI*2,0,Math.PI*.52),material(hair));torso.position.y=1.28;head.position.y=1.96;hairMesh.position.y=2.05;g.add(torso,head,hairMesh);const face=material(0x1d1a17);for(const x of[-.105,.105]){const eye=new THREE.Mesh(new THREE.SphereGeometry(.032,7,5),face);eye.position.set(x,2,.286);g.add(eye)}const armGeo=new THREE.CylinderGeometry(.095,.11,.70,6),legGeo=new THREE.CylinderGeometry(.12,.14,.70,6),armL=new THREE.Mesh(armGeo,material(outfit)),armR=armL.clone(),legL=new THREE.Mesh(legGeo,material(accent)),legR=legL.clone();armL.position.set(-.45,1.25,0);armR.position.set(.45,1.25,0);legL.position.set(-.19,.47,0);legR.position.set(.19,.47,0);g.add(armL,armR,legL,legR);for(const x of[-.19,.19])box(g,0x332a22,[.25,.18,.38],[x,.1,.07]);if(pack)box(g,0x5c4934,[.58,.72,.28],[0,1.3,-.34]);g.userData.rig={armL,armR,legL,legR,torso,head,hairMesh};g.traverse(o=>{if(o.isMesh)o.castShadow=true});return g}
function animateHumanoid(g,moving,t){const r=g.userData.rig,a=moving?Math.sin(t*.012)*.52:0;r.legL.rotation.x=a;r.legR.rotation.x=-a;r.armL.rotation.x=-a*.72;r.armR.rotation.x=a*.72;r.torso.position.y=1.28+(moving?Math.abs(Math.sin(t*.012))*.018:Math.sin(t*.0025)*.008);r.head.position.y=1.96+(moving?Math.abs(Math.sin(t*.012))*.012:Math.sin(t*.0025)*.006);r.hairMesh.position.y=2.05+r.head.position.y-1.96}

function bed(x,z){const g=new THREE.Group();g.position.set(x,0,z);box(g,0x5a3b27,[3,.55,1.9],[0,.38,0]);box(g,0xcab990,[2.75,.28,1.7],[0,.76,0]);box(g,0xe2d5b8,[.75,.24,1.45],[-.85,.98,0]);box(g,0x6f3f35,[1.9,.08,1.72],[.35,.94,0]);scene.add(g);block(x,z,3,1.9);return g}
function hearth(x,z){const g=new THREE.Group();g.position.set(x,0,z);box(g,0x675342,[2.3,1.4,1.4],[0,.7,0]);box(g,0x2a211b,[1.25,.75,.22],[0,.67,.72]);for(const px of[-.28,0,.28]){const flame=new THREE.Mesh(new THREE.ConeGeometry(.18,.75,7),material(px?0xe66d28:0xffc34d,.55));flame.position.set(px,.72,.83);g.add(flame)}const light=new THREE.PointLight(0xff8b35,5,8);light.position.set(0,1.4,1);g.add(light);g.userData.fire=light;scene.add(g);block(x,z,2.3,1.4);return g}
function table(x,z,large=false){const g=new THREE.Group();g.position.set(x,0,z);const w=large?4.8:2.7,d=large?2.4:1.5;box(g,0x68472e,[w,.28,d],[0,1.05,0]);for(const px of[-w*.4,w*.4])for(const pz of[-d*.32,d*.32])box(g,0x503520,[.22,1,.22],[px,.5,pz]);scene.add(g);block(x,z,w,d);return g}
function shelves(x,z){const g=new THREE.Group();g.position.set(x,0,z);box(g,0x523721,[2.6,3.3,.45],[0,1.65,0]);for(const y of[.55,1.55,2.55])box(g,0x8a623d,[2.35,.12,.8],[0,y,.2]);for(const [px,y,c] of[[-.7,.83,0x6d4830],[.15,.82,0x7d6a3e],[.75,1.82,0x5f4933],[-.45,2.82,0x7b5734]])box(g,c,[.48,.5,.52],[px,y,.28]);scene.add(g);block(x,z,2.7,1);return g}
function crates(x,z){const g=new THREE.Group();g.position.set(x,0,z);for(const [px,pz,s] of[[-.6,0,1.15],[.65,.15,1],[-.1,-.55,.85]]){box(g,0x89603a,[s,s,s],[px,s/2,pz]);box(g,0x4d3524,[s+.03,.08,s+.03],[px,s*.55,pz])}scene.add(g);block(x,z,2.5,1.8);return g}
function anvil(x,z){const g=new THREE.Group();g.position.set(x,0,z);box(g,0x3d4242,[.65,1,.65],[0,.5,0]);box(g,0x555b5c,[1.8,.38,.72],[0,1.12,0],.55);const horn=new THREE.Mesh(new THREE.ConeGeometry(.34,.9,8),material(0x555b5c,.55));horn.rotation.z=-Math.PI/2;horn.position.set(1.08,1.12,0);g.add(horn);scene.add(g);block(x,z,2.2,1);return g}
function wallFeature(kind,x,z){const g=new THREE.Group();g.position.set(x,0,z);box(g,0x4b3422,[2.6,2,.22],[0,2.25,0]);box(g,kind==='map'?0xd0bc82:0x765337,[2.25,1.65,.08],[0,2.25,.16]);scene.add(g);return g}
function herbTable(x,z){const g=table(x,z);for(const [px,pz,c] of[[-.55,0,0x709854],[.25,.15,0x8cab61],[.7,-.2,0x526d43]]){const herb=new THREE.Mesh(new THREE.ConeGeometry(.18,.65,6),material(c));herb.position.set(px,1.48,pz);g.add(herb)}return g}
function addObject([name,kind,x,z,message]){let object;if(kind==='bed')object=bed(x,z);else if(kind==='hearth')object=hearth(x,z);else if(kind==='desk')object=table(x,z);else if(kind==='table')object=table(x,z,true);else if(kind==='shelves')object=shelves(x,z);else if(kind==='crates')object=crates(x,z);else if(kind==='anvil')object=anvil(x,z);else if(kind==='herbs')object=herbTable(x,z);else object=wallFeature(kind,x,z);register(name,object,2.6,message)}

function buildRoom(){scene=new THREE.Scene();scene.background=new THREE.Color(0x191510);scene.fog=new THREE.Fog(0x191510,18,34);camera=new THREE.PerspectiveCamera(45,1,.1,80);renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;worldEl.replaceChildren(renderer.domElement);scene.add(new THREE.HemisphereLight(0xffe5be,0x2a211b,1.65));const sun=new THREE.DirectionalLight(0xffd9a0,2.25);sun.position.set(6,11,7);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);scene.add(sun);const room=new THREE.Group();scene.add(room);box(room,config.floor,[15,.45,13],[0,-.22,0]);for(let x=-7;x<=7;x+=1)box(room,0x493221,[.035,.015,13],[x,.015,0]);box(room,config.wall,[15,4.5,.45],[0,2.25,-6.5]);box(room,config.wall,[.45,4.5,13],[-7.5,2.25,0]);box(room,config.wall,[.45,4.5,13],[7.5,2.25,0]);for(const x of[-7.2,0,7.2])box(room,config.trim,[.25,4.8,.55],[x,2.4,-6.35]);for(const z of[-5.9,0,5.9]){box(room,config.trim,[.55,4.8,.25],[-7.35,2.4,z]);box(room,config.trim,[.55,4.8,.25],[7.35,2.4,z])}for(const x of[-4,4]){box(room,0x4b3422,[2.25,2.4,.22],[x,2.45,-6.25]);box(room,0x7190a0,[1.75,1.9,.07],[x,2.45,-6.08],.4);box(room,config.trim,[.10,1.9,.1],[x,2.45,-6.01]);box(room,config.trim,[1.75,.1,.1],[x,2.45,-6.01])}box(room,config.trim,[3.1,.32,.55],[0,.16,6.25]);box(room,0x2d2119,[2.2,3,.35],[0,1.5,6.35]);for(const item of config.objects)addObject(item);const resident=humanoid({outfit:config.residentColor,pack:false});resident.position.set(-2.2,0,-1.5);resident.rotation.y=.5;scene.add(resident);register(config.resident,resident,2.5,`${config.resident}: “This room is becoming part of the settlement’s life.”`);player=humanoid();player.position.set(0,0,4);scene.add(player);const shadow=new THREE.Mesh(new THREE.CircleGeometry(.7,18),new THREE.MeshBasicMaterial({color:0,transparent:true,opacity:.22,depthWrite:false}));shadow.rotation.x=-Math.PI/2;shadow.position.y=.02;player.add(shadow);const exit=new THREE.Object3D();exit.position.set(0,0,5.85);scene.add(exit);register('exit to world',exit,1.4,'Leave the building.');camera.position.set(8,9,11);clock=new THREE.Clock();resize();running=true;loading.hidden=true;animate();showToast(`${config.name} · Level ${level}`)}
function isBlocked(x,z){if(x<-6.75||x>6.75||z<-5.75||z>5.8)return true;return blockers.some(b=>x>b.minX&&x<b.maxX&&z>b.minZ&&z<b.maxZ)}
function updatePlayer(dt,t){desired.set(joystickX,0,joystickY);if(keys.has('w')||keys.has('arrowup'))desired.z-=1;if(keys.has('s')||keys.has('arrowdown'))desired.z+=1;if(keys.has('a')||keys.has('arrowleft'))desired.x-=1;if(keys.has('d')||keys.has('arrowright'))desired.x+=1;const strength=Math.min(1,desired.length());if(strength){desired.normalize().multiplyScalar(4.6*strength);velocity.lerp(desired,Math.min(1,dt*10));player.rotation.y=Math.atan2(velocity.x,velocity.z)}else velocity.lerp(new THREE.Vector3(),Math.min(1,dt*9));const nx=player.position.x+velocity.x*dt,nz=player.position.z+velocity.z*dt;if(!isBlocked(nx,player.position.z))player.position.x=nx;if(!isBlocked(player.position.x,nz))player.position.z=nz;animateHumanoid(player,strength>.05,t);cameraTarget.copy(player.position).add(new THREE.Vector3(8,9,9));camera.position.lerp(cameraTarget,Math.min(1,dt*3.8));camera.lookAt(player.position.x,.7,player.position.z)}
function updateNearest(){let best=null,dist=Infinity;for(const item of interactables){const d=player.position.distanceTo(item.object.position);if(d<item.radius&&d<dist){best=item;dist=d}}nearest=best;promptEl.hidden=!nearest;if(nearest)promptEl.textContent=nearest.name==='exit to world'?'Exit to world':`Interact with ${nearest.name}`}
function leaveInterior(){window.location.assign(new URL('./index.html',window.location.href).href)}
function interact(){if(!nearest)return;if(nearest.name==='exit to world'){leaveInterior();return}showToast(nearest.message)}
function showToast(message){toastEl.textContent=message;toastEl.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toastEl.classList.remove('show'),3000)}
function resize(){if(!renderer)return;const w=worldEl.clientWidth,h=worldEl.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}
function animate(t=0){if(!running)return;requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05);updatePlayer(dt,t);updateNearest();for(const item of interactables){const fire=item.object.userData.fire;if(fire)fire.intensity=4.6+Math.sin(t*.012)*.7+Math.sin(t*.027)*.35}renderer.render(scene,camera)}

window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(k)){keys.add(k);e.preventDefault()}if(k==='e'||k===' '){interact();e.preventDefault()}});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{keys.clear();resetJoystick()});window.addEventListener('resize',resize);actionButton.addEventListener('click',interact);exitWorld.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();leaveInterior()});
const joystick=document.getElementById('joystick'),joystickKnob=document.getElementById('joystickKnob');
function updateJoystick(e){const r=joystick.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,max=r.width*.32;let dx=e.clientX-cx,dy=e.clientY-cy;const dist=Math.hypot(dx,dy);if(dist>max){dx=dx/dist*max;dy=dy/dist*max}joystickX=dx/max;joystickY=dy/max;if(Math.hypot(joystickX,joystickY)<.12)joystickX=joystickY=0;joystickKnob.style.transform=`translate(calc(-50% + ${dx}px),calc(-50% + ${dy}px))`}
function resetJoystick(){joystickPointer=null;joystickX=joystickY=0;joystick.classList.remove('active');joystickKnob.style.transform='translate(-50%,-50%)'}
joystick.addEventListener('pointerdown',e=>{e.preventDefault();joystickPointer=e.pointerId;joystick.setPointerCapture?.(e.pointerId);joystick.classList.add('active');updateJoystick(e)});joystick.addEventListener('pointermove',e=>{if(e.pointerId===joystickPointer)updateJoystick(e)});joystick.addEventListener('pointerup',e=>{if(e.pointerId===joystickPointer)resetJoystick()});joystick.addEventListener('pointercancel',resetJoystick);
async function load(){retry.hidden=true;if(!config){loadingTitle.textContent='Unknown building';loadingMessage.textContent='Return to town upgrades and choose an available building.';return}document.getElementById('buildingName').textContent=config.name;loadingTitle.textContent=`Opening ${config.name}…`;const abort=new AbortController(),timer=setTimeout(()=>abort.abort(),8000);try{const response=await fetch('/.netlify/functions/town-upgrades',{cache:'no-store',signal:abort.signal});if(!response.ok)throw Error(`HTTP ${response.status}`);const data=await response.json();if(!data.ok||!data.levels)throw Error('Upgrade data unavailable');level=Number(data.levels[id]||1);if(level<2){loadingTitle.textContent=`${config.name} is still closed`;loadingMessage.textContent='Upgrade this building to Level 2 before entering.';return}buildRoom()}catch(error){loadingTitle.textContent='The building would not open';loadingMessage.textContent=error.name==='AbortError'?'The settlement took too long to respond. Try again.':'The shared building level could not be verified. Try again.';retry.hidden=false;console.error(error)}finally{clearTimeout(timer)}}
retry.addEventListener('click',load);load();
