[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/interior.html"
  [headers.values]
    Cache-Control = "no-store, max-age=0, must-revalidate"

[[headers]]
  for = "/interior.js"
  [headers.values]
    Cache-Control = "no-store, max-age=0, must-revalidate"

[[headers]]
  for = "/town.html"
  [headers.values]
    Cache-Control = "no-store, max-age=0, must-revalidate"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-store, max-age=0, must-revalidate"

[[headers]]
  for = "/main.js"
  [headers.values]
    Cache-Control = "no-store, max-age=0, must-revalidate"
