import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/+esm';

const API='/.netlify/functions/private-world',CLIENT_KEY='gptworld-client-id';
const worldEl=document.getElementById('world'),loading=document.getElementById('loading'),loadingTitle=document.getElementById('loadingTitle'),loadingMessage=document.getElementById('loadingMessage'),retry=document.getElementById('retry'),returnTown=document.getElementById('returnTown'),promptEl=document.getElementById('prompt'),toastEl=document.getElementById('toast'),actionButton=document.getElementById('actionButton');
const inventoryEls={wood:document.getElementById('woodCount'),stone:document.getElementById('stoneCount'),herbs:document.getElementById('herbCount')};
let renderer,scene,camera,player,clock,running=false,joystickX=0,joystickY=0,joystickPointer=null,toastTimer,nearest=null,lastSave=0,saveBusy=false;
const keys=new Set(),velocity=new THREE.Vector3(),desired=new THREE.Vector3(),cameraTarget=new THREE.Vector3(),interactables=[];

function box(parent,color,size,pos){const m=new THREE.Mesh(new THREE.BoxGeometry(...size),new THREE.MeshStandardMaterial({color,roughness:.94}));m.position.set(...pos);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function humanoid(){const g=new THREE.Group(),mat=c=>new THREE.MeshStandardMaterial({color:c,roughness:.95});const torso=new THREE.Mesh(new THREE.CylinderGeometry(.34,.43,.86,8),mat(0x8b7650)),head=new THREE.Mesh(new THREE.SphereGeometry(.3,12,9),mat(0xe0b586)),armGeo=new THREE.CylinderGeometry(.095,.11,.7,6),legGeo=new THREE.CylinderGeometry(.12,.14,.7,6),armL=new THREE.Mesh(armGeo,mat(0x8b7650)),armR=armL.clone(),legL=new THREE.Mesh(legGeo,mat(0x49392c)),legR=legL.clone();torso.position.y=1.28;head.position.y=1.96;armL.position.set(-.45,1.25,0);armR.position.set(.45,1.25,0);legL.position.set(-.19,.47,0);legR.position.set(.19,.47,0);g.add(torso,head,armL,armR,legL,legR);box(g,0x5c4934,[.58,.72,.28],[0,1.3,-.34]);g.userData.rig={torso,head,armL,armR,legL,legR};g.traverse(o=>{if(o.isMesh)o.castShadow=true;});return g;}
function animatePerson(g,moving,t){const r=g.userData.rig,a=moving?Math.sin(t*.012)*.52:0;r.legL.rotation.x=a;r.legR.rotation.x=-a;r.armL.rotation.x=-a*.72;r.armR.rotation.x=a*.72;r.torso.position.y=1.28+(moving?Math.abs(Math.sin(t*.012))*.018:0);}
function tree(o){const g=new THREE.Group();g.position.set(o.x,0,o.z);const s=o.scale||1;box(g,0x6f4d2f,[.55*s,2.3*s,.55*s],[0,1.15*s,0]);const crown=new THREE.Mesh(new THREE.ConeGeometry(1.45*s,3.2*s,7),new THREE.MeshStandardMaterial({color:0x365b35,roughness:1}));crown.position.y=3.2*s;crown.castShadow=true;g.add(crown);scene.add(g);interactables.push({label:'young forest',message:'This tree is part of your persistent private ecology.',object:g,radius:2.1});}
function rock(o){const m=new THREE.Mesh(new THREE.DodecahedronGeometry(.85*(o.scale||1),0),new THREE.MeshStandardMaterial({color:0x77796f,roughness:1}));m.position.set(o.x,.55,o.z);m.scale.y=.7;m.castShadow=true;scene.add(m);interactables.push({label:'stone deposit',message:'A persistent stone deposit rests beneath the surface.',object:m,radius:1.9});}
function herbs(o){const g=new THREE.Group();g.position.set(o.x,0,o.z);for(let i=0;i<5;i++){const m=new THREE.Mesh(new THREE.ConeGeometry(.13,.7,5),new THREE.MeshStandardMaterial({color:0x7aa35a,roughness:1}));m.position.set((i%3-.8)*.28,.35,(i%2-.5)*.35);g.add(m);}scene.add(g);interactables.push({label:'wild herbs',message:'These herbs are tracked by your private world.',object:g,radius:1.7});}
function wildlife(o){const g=new THREE.Group();g.position.set(o.x,0,o.z);g.rotation.y=o.heading||0;const body=new THREE.Mesh(new THREE.SphereGeometry(.55,9,7),new THREE.MeshStandardMaterial({color:0x96784e,roughness:1}));body.scale.set(1.4,.75,.65);body.position.y=.9;g.add(body);for(const x of[-.42,.42])for(const z of[-.22,.22])box(g,0x604c32,[.11,.72,.11],[x,.4,z]);scene.add(g);interactables.push({label:'wildlife',message:'Wildlife populations persist here and advance only in bounded offline steps.',object:g,radius:2.4});}
function build(data){const terrain=data.world.terrain,ecology=data.world.ecology;scene=new THREE.Scene();scene.background=new THREE.Color(0x8fb1b1);scene.fog=new THREE.Fog(0x8fb1b1,38,96);camera=new THREE.PerspectiveCamera(45,1,.1,200);renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;worldEl.replaceChildren(renderer.domElement);scene.add(new THREE.HemisphereLight(0xbfe3ff,0x38442d,2.2));const sun=new THREE.DirectionalLight(0xfff0cf,2.5);sun.position.set(15,24,10);sun.castShadow=true;scene.add(sun);const ground=new THREE.Mesh(new THREE.BoxGeometry(terrain.size,1,terrain.size),new THREE.MeshStandardMaterial({color:0x667d4e,roughness:1}));ground.position.y=-.5;ground.receiveShadow=true;scene.add(ground);const water=new THREE.Mesh(new THREE.CylinderGeometry(terrain.water.radius,terrain.water.radius,.16,28),new THREE.MeshStandardMaterial({color:0x4d8090,roughness:.35,transparent:true,opacity:.9}));water.position.set(terrain.water.x,.02,terrain.water.z);scene.add(water);const farm=new THREE.Mesh(new THREE.BoxGeometry(terrain.farmland.width,.04,terrain.farmland.depth),new THREE.MeshStandardMaterial({color:0x806b42,roughness:1}));farm.position.set(terrain.farmland.x,.03,terrain.farmland.z);scene.add(farm);const home=new THREE.Group();home.position.set(terrain.homestead.x,0,terrain.homestead.z);box(home,0x8b7658,[4.5,2.8,4],[0,1.4,0]);const roof=new THREE.Mesh(new THREE.ConeGeometry(3.6,1.8,4),new THREE.MeshStandardMaterial({color:0x4c3529,roughness:1}));roof.position.y=3.65;roof.rotation.y=Math.PI/4;home.add(roof);scene.add(home);for(const o of terrain.objects){if(o.kind==='tree')tree(o);else if(o.kind==='rock')rock(o);else if(o.kind==='herbs')herbs(o);else wildlife(o);}player=humanoid();player.position.set(Number(data.session.position.x)||0,0,Number(data.session.position.z)||8);scene.add(player);camera.position.set(player.position.x+12,14,player.position.z+12);clock=new THREE.Clock();document.getElementById('worldName').textContent=data.world.name;document.getElementById('season').textContent=ecology.season;document.getElementById('weather').textContent=String(ecology.weather||'clear').replace(/^./,c=>c.toUpperCase());for(const [key,el] of Object.entries(inventoryEls))el.textContent=Number(data.inventory[key]||0);loading.hidden=true;running=true;resize();animate();if(data.catchUp.steps)showToast(`Your world advanced ${data.catchUp.steps} offline ecology step${data.catchUp.steps===1?'':'s'}.`);}
function showToast(message){toastEl.textContent=message;toastEl.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toastEl.classList.remove('show'),3200);}
function updatePlayer(dt,t){desired.set(joystickX,0,joystickY);if(keys.has('w')||keys.has('arrowup'))desired.z-=1;if(keys.has('s')||keys.has('arrowdown'))desired.z+=1;if(keys.has('a')||keys.has('arrowleft'))desired.x-=1;if(keys.has('d')||keys.has('arrowright'))desired.x+=1;const strength=Math.min(1,desired.length());if(strength){desired.normalize().multiplyScalar(5.2*strength);velocity.lerp(desired,Math.min(1,dt*10));player.rotation.y=Math.atan2(velocity.x,velocity.z);}else velocity.lerp(new THREE.Vector3(),Math.min(1,dt*9));player.position.x=Math.max(-33,Math.min(33,player.position.x+velocity.x*dt));player.position.z=Math.max(-33,Math.min(33,player.position.z+velocity.z*dt));animatePerson(player,strength>.05,t);cameraTarget.copy(player.position).add(new THREE.Vector3(12,14,12));camera.position.lerp(cameraTarget,Math.min(1,dt*3.5));camera.lookAt(player.position.x,.5,player.position.z);}
function updateNearest(){let best=null,distance=Infinity;for(const item of interactables){const d=player.position.distanceTo(item.object.position);if(d<item.radius&&d<distance){best=item;distance=d;}}nearest=best;promptEl.hidden=!best;if(best)promptEl.textContent=`Inspect ${best.label}`;}
function interact(){if(nearest)showToast(nearest.message);}
async function savePosition(){if(!running||saveBusy)return;saveBusy=true;try{await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({clientId:localStorage.getItem(CLIENT_KEY),action:'save_position',position:{x:Number(player.position.x.toFixed(3)),z:Number(player.position.z.toFixed(3))}})});}catch{}finally{saveBusy=false;}}
function requestKey(action){return`${action}-${Date.now()}-${crypto.randomUUID?.()||Math.random().toString(36).slice(2)}`;}
async function leave(){if(!running)return;returnTown.disabled=true;await savePosition();try{const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({clientId:localStorage.getItem(CLIENT_KEY),action:'return_public',idempotencyKey:requestKey('return'),position:{x:player.position.x,z:player.position.z}})}),data=await r.json();if(!data.ok)throw Error(data.error||'return_failed');sessionStorage.setItem('gptworld-public-spawn',JSON.stringify(data.position));location.assign('./index.html?from=private');}catch{showToast('Return failed. Your world remains saved; try again.');returnTown.disabled=false;}}
function resize(){if(!renderer)return;const w=worldEl.clientWidth,h=worldEl.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}
function animate(t=0){if(!running)return;requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05);updatePlayer(dt,t);updateNearest();if(t-lastSave>5000){savePosition();lastSave=t;}renderer.render(scene,camera);}
async function load(){retry.hidden=true;const clientId=localStorage.getItem(CLIENT_KEY);if(!clientId){loadingTitle.textContent='No registered traveler';loadingMessage.textContent='Enter the public town first so the server can identify your world owner.';return;}try{const r=await fetch(`${API}?clientId=${encodeURIComponent(clientId)}`,{cache:'no-store'}),data=await r.json();if(!data.ok)throw Error(data.error||'load_failed');build(data);}catch(error){loadingTitle.textContent='Your world could not open';loadingMessage.textContent=error.message==='living_worlds_migration_required'?'The Living Worlds database migration has not been applied.':'Your public progress is safe. Try loading the private world again.';retry.hidden=false;}}
window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(k)){keys.add(k);e.preventDefault();}if(k==='e'||k===' '){interact();e.preventDefault();}});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('resize',resize);window.addEventListener('pagehide',()=>{if(running)navigator.sendBeacon?.(API,new Blob([JSON.stringify({clientId:localStorage.getItem(CLIENT_KEY),action:'save_position',position:{x:player.position.x,z:player.position.z}})],{type:'application/json'}));});
actionButton.addEventListener('click',interact);returnTown.addEventListener('click',leave);retry.addEventListener('click',load);
const joystick=document.getElementById('joystick'),joystickKnob=document.getElementById('joystickKnob');function updateJoystick(e){const r=joystick.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,max=r.width*.32;let dx=e.clientX-cx,dy=e.clientY-cy,d=Math.hypot(dx,dy);if(d>max){dx=dx/d*max;dy=dy/d*max;}joystickX=dx/max;joystickY=dy/max;if(Math.hypot(joystickX,joystickY)<.12)joystickX=joystickY=0;joystickKnob.style.transform=`translate(calc(-50% + ${dx}px),calc(-50% + ${dy}px))`;};function resetJoystick(){joystickPointer=null;joystickX=joystickY=0;joystick.classList.remove('active');joystickKnob.style.transform='translate(-50%,-50%)';}joystick.addEventListener('pointerdown',e=>{e.preventDefault();joystickPointer=e.pointerId;joystick.setPointerCapture?.(e.pointerId);joystick.classList.add('active');updateJoystick(e);});joystick.addEventListener('pointermove',e=>{if(e.pointerId===joystickPointer)updateJoystick(e);});joystick.addEventListener('pointerup',e=>{if(e.pointerId===joystickPointer)resetJoystick();});joystick.addEventListener('pointercancel',resetJoystick);
load();
