const panel=document.createElement('section');
panel.id='wildlifeJournalPanel';
panel.setAttribute('aria-label','Wildlife journal');
panel.style.cssText='position:fixed;top:76px;right:12px;z-index:25;width:min(350px,calc(100vw - 24px));max-height:65vh;overflow:auto;background:#14231c;color:#f2f0df;border:1px solid #8b9b72;border-radius:12px;padding:14px;box-shadow:0 10px 30px #0009;font:14px/1.5 system-ui';
panel.hidden=true;
const button=document.createElement('button');button.type='button';button.textContent='Wildlife Journal';button.setAttribute('aria-controls',panel.id);button.setAttribute('aria-expanded','false');button.style.cssText='position:fixed;top:76px;right:12px;z-index:24;background:#253d2d;color:#fff;border:1px solid #a5b788;border-radius:10px;padding:9px 12px;cursor:pointer';
const heading=document.createElement('h2');heading.textContent='Wildlife Journal';heading.style.margin='0 0 8px';
const close=document.createElement('button');close.type='button';close.textContent='Close';close.style.cssText='float:right;background:#304636;color:white;border:1px solid #889b77;border-radius:6px;padding:5px 9px';
const content=document.createElement('div');content.setAttribute('aria-live','polite');
panel.append(close,heading,content);document.body.append(button,panel);
function show(open){panel.hidden=!open;button.hidden=open;button.setAttribute('aria-expanded',String(open));if(open)load();}
button.addEventListener('click',()=>show(true));close.addEventListener('click',()=>show(false));
const pct=v=>`${Math.round(Math.max(0,Math.min(1,Number(v)||0))*100)}%`;
function line(parent,text){const p=document.createElement('p');p.textContent=text;p.style.margin='6px 0';parent.append(p);}
async function load(){content.replaceChildren();line(content,'Loading wildlife records…');try{const response=await fetch('/.netlify/functions/world',{cache:'no-store'});if(!response.ok)throw Error(`Server returned ${response.status}`);const data=await response.json();if(!data.ok)throw Error(data.error||'World unavailable');const eco=data.ecosystem||data.world?.ecosystem||{};content.replaceChildren();const summary=eco.wildlifeSummary;line(content,summary?`Year ${summary.year} · ${summary.animals} animals · ${summary.young} young · ${summary.injured} injured`:'Wildlife records begin after the next ecological year.');for(const sp of (eco.species||[]).filter(s=>s.kind!=='plant')){const section=document.createElement('section');section.style.cssText='border-top:1px solid #50614c;padding:8px 0';const h=document.createElement('strong');h.textContent=`${sp.name} · ${sp.population||0}`;section.append(h);line(section,`Young: ${sp.ageCohorts?.young??'—'} · Adults: ${sp.ageCohorts?.adults??'—'} · Injured: ${sp.injuries?.injured??'—'}`);if(sp.needs)line(section,`Hunger ${pct(sp.needs.hunger)} · Thirst ${pct(sp.needs.thirst)} · Energy ${pct(sp.needs.energy)}`);content.append(section);}const entries=(eco.wildlifeJournal||[]).slice(-12).reverse();const title=document.createElement('h3');title.textContent='Recent events';content.append(title);if(!entries.length)line(content,'No life-cycle events recorded yet.');for(const event of entries)line(content,`Year ${event.year}: ${event.text||event.type}`);}catch(error){content.replaceChildren();line(content,`Unable to load wildlife records: ${error.message}`);}}
