from pathlib import Path
p=Path('index.html'); s=p.read_text()
old='<section id="welcome" class="welcome" aria-modal="true" role="dialog" aria-labelledby="welcomeTitle"><div class="welcome-card"><div class="eyebrow">A LIVING WORLD EXPERIMENT</div><h2 id="welcomeTitle">Welcome to Day 4.</h2><p>Travel beyond the completed Western Crossing has begun to leave a mark. A short survey trail and marker now extend onto the western bank, where travelers can gather from newly mapped resources.</p><p>The settlement remains well supplied, so this is a cautious step outward rather than a major expansion. Explore, gather, contribute, and leave a history behind.</p><label>Traveler name<input id="playerName" maxlength="20" autocomplete="nickname" value="Traveler" /></label><button id="enterWorld" type="button">Enter GPTWorld</button><small>On phones, drag the joystick to move and use Interact near people and resources. On a keyboard, use WASD / arrow keys and E.</small></div></section>'
new='''<section id="welcome" class="welcome" aria-modal="true" role="dialog" aria-labelledby="welcomeTitle"><div class="welcome-card"><div class="eyebrow">GPTWORLD · A WORLD THAT KEEPS CHANGING</div><h2 id="welcomeTitle">Enter the living world.</h2><p>GPTWorld does not reset when you leave. Weather and seasons continue, plants and animals live inside their own simulation, disasters can reshape the land, and the settlement changes through what travelers do.</p><p>Each world day, GPT can observe what happened and evolve the world or gameplay. Your gathering, exploration, construction and other choices become part of the shared history future travelers inherit.</p><div id="returningTraveler" hidden><strong>Welcome back.</strong><p>Choose one of your travelers on this device:</p><div id="knownNames" class="known-names"></div><button id="newTraveler" type="button" class="secondary">Create another traveler</button></div><div id="newTravelerForm"><label>Create your traveler<input id="playerName" maxlength="20" autocomplete="nickname" value="" placeholder="Traveler name" /></label><div id="nameError" role="alert" hidden></div></div><button id="enterWorld" type="button">Enter GPTWorld</button><small>Names must be appropriate. On phones, use the joystick to move and Interact near people, animals, resources and world features.</small></div></section>'''
assert old in s; s=s.replace(old,new,1)
# replace old auto-resume: returning users now choose their saved name
start=s.index('  <script>\n    (()=>{')
end=s.index('  </script>',start)+len('  </script>')
replacement='''  <script>\n    (()=>{\n      const NAME_KEY='gptworld-known-names';\n      const saved=()=>{try{return JSON.parse(localStorage.getItem(NAME_KEY)||'[]').filter(Boolean)}catch{return[]}};\n      const legacy=()=>{try{return JSON.parse(localStorage.getItem('gptworld-day1')||'null')?.playerName||''}catch{return''}};\n      const init=()=>{\n        let names=saved(); const old=legacy(); if(old&&old!=='Traveler'&&!names.includes(old)){names.unshift(old);localStorage.setItem(NAME_KEY,JSON.stringify(names.slice(0,6)))}\n        const returning=document.getElementById('returningTraveler'),box=document.getElementById('knownNames'),form=document.getElementById('newTravelerForm'),input=document.getElementById('playerName'),fresh=document.getElementById('newTraveler');\n        if(names.length){returning.hidden=false;form.hidden=true;names.slice(0,6).forEach((name,i)=>{const b=document.createElement('button');b.type='button';b.className='known-name';b.textContent=name;b.addEventListener('click',()=>{input.value=name;box.querySelectorAll('button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});box.appendChild(b)});box.firstElementChild?.click()}\n        fresh?.addEventListener('click',()=>{form.hidden=false;input.value='';input.focus()});\n      };\n      if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();\n    })();\n  </script>'''
s=s[:start]+replacement+s[end:]
p.write_text(s)

p=Path('main.js'); s=p.read_text()
old="function startGame(){playerName=(playerNameEl.value||'Traveler').trim().slice(0,20)||'Traveler';ensureClientId();gameStarted=true;"
new="""function validTravelerName(raw){const name=String(raw||'').trim().replace(/\\s+/g,' ').slice(0,20);if(name.length<2)return{ok:false,error:'Choose a name with at least 2 characters.'};if(!/^[A-Za-z0-9][A-Za-z0-9 _'-]*$/.test(name))return{ok:false,error:'Use letters, numbers, spaces, apostrophes or hyphens only.'};const compact=name.toLowerCase().replace(/[^a-z]/g,'');const blocked=['fuck','shit','bitch','cunt','nigger','nigga','faggot','retard','whore','slut','asshole','dick','penis','vagina','nazi','hitler'];if(blocked.some(x=>compact.includes(x)))return{ok:false,error:'That traveler name is not allowed. Choose another.'};return{ok:true,name}}
function rememberTravelerName(name){try{const key='gptworld-known-names',names=JSON.parse(localStorage.getItem(key)||'[]').filter(Boolean).filter(n=>n!==name);names.unshift(name);localStorage.setItem(key,JSON.stringify(names.slice(0,6)))}catch{}}
function startGame(){const checked=validTravelerName(playerNameEl.value);const errorEl=document.getElementById('nameError');if(!checked.ok){if(errorEl){errorEl.textContent=checked.error;errorEl.hidden=false}playerNameEl.focus();return}if(errorEl)errorEl.hidden=true;playerName=checked.name;rememberTravelerName(playerName);ensureClientId();gameStarted=true;"""
assert old in s; s=s.replace(old,new,1)
p.write_text(s)
